### ISSUE TITLE
Touchdesigner is not responding

### ISSUE THREAD

**Issue by guidoschmidt** [GregFinger/TD-Curve_Editor#1]
Hey Greg,

I just tried to use the Curve Editor .tox component, but Touchdesigner freezes when I drag in the component, have you experienced similar issues? Haven't tried to look at the python scripts yet though.

I'm using non-commercial Touchdesigner version 2019.3384 64-Bit build.

**Comment by GregFinger** [comment]
Ya, there's issues with it in the experimental build. I found the bug (it's a Text SOP bug) and have submitted it to Derivative. It should work fine in the stable build though (2019.19930). If it's necessary for you to work in the experimental build though, I can arrange a quick fix for you.

**Comment by guidoschmidt** [comment]
All good, it's not urgent - I was just trying it out. Thanks for the fast reply 👍
