### ISSUE TITLE
Doesn't seem to work in latest 2020 stable

### ISSUE THREAD

**Issue by drmbt** [GregFinger/TD-Curve_Editor#2]
breaks on any interaction in a clean session

**Comment by GregFinger** [comment]
Should be fixed now. I guess with the updated python version, it broke something in numpy.

The **interpolate** script was giving the error on line 414

> numpy.float64 object cannot be interpreted as an integer

so i had to directly convert the numpy array to int: `int(np.prod(self.c.shape[2:]))`

let me know if there's still issues
